// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID      int32
	UserID  int32
	Balance pgtype.Numeric
}

type User struct {
	ID    int32
	Name  string
	Email string
}
