// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, ssn)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
	Ssn      pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Ssn,
	)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING id, name, email
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, user_id, balance FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.UserID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAndAccount = `-- name: GetUserAndAccount :many
SELECT users.id, users.name, users.email, accounts.id, accounts.user_id, accounts.balance FROM users JOIN accounts ON users.id = accounts.user_id
`

type GetUserAndAccountRow struct {
	ID      int32
	Name    string
	Email   string
	ID_2    int32
	UserID  int32
	Balance pgtype.Numeric
}

func (q *Queries) GetUserAndAccount(ctx context.Context) ([]GetUserAndAccountRow, error) {
	rows, err := q.db.Query(ctx, getUserAndAccount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAndAccountRow
	for rows.Next() {
		var i GetUserAndAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ID_2,
			&i.UserID,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUserWithAlias = `-- name: GetUserWithAlias :many
SELECT u.id, u.name, u.email FROM users u
`

func (q *Queries) GetUserWithAlias(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserWithAlias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2 WHERE id = $1 RETURNING id, name, email
`

type UpdateUserParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
